/*
 * DIO_cnfg.c
 *
 *  Created on: Sep 22, 2019
 *      Author: Mohammed
 */


#include "Switch_cnfg.h"



Switch_Cnfg_t Switch_Cnfg_arr[NUMBER_OF_SWITCHES] =
{
	
		{SWITCH_OFF_PORT_DR,SWITCH_OFF_PIN,INPUT,PULLUP,INITIALIZED},   // SWITCH_ON
		{SWITCH_ON_PORT_DR,SWITCH_ON_PIN,INPUT,PULLUP,INITIALIZED},    //SWITCH_OFF
		{SWITCH_ON_PORT_DR_MIRROR,SWITCH_ON_PIN_MIRROR,INPUT,PULLUP,INITIALIZED}    //SWITCH_PLUS
		
		/*
		{PORT_A,0,INPUT,PULLUP,INITIALIZED},   // SWITCH_MINUS
		{PORT_A,1,INPUT,PULLUP,INITIALIZED}    //SWITCH_PLUS
			*/
};


