/*
 * DIO_cnfg.c
 *
 *  Created on: Sep 22, 2019
 *      Author: Mohammed
 */


#include "Switch_cnfg.h"



Switch_Cnfg_t Switch_Cnfg_arr[NUMBER_OF_SWITCHES] =
{
	
		{SWITCH_MINUS_PORT_DR,SWITCH_MINUS_PIN,INPUT,PULLUP,INITIALIZED},   // SWITCH_MINUS
		{SWITCH_PLUS_PORT_DR,SWITCH_PLUS_PIN,INPUT,PULLUP,INITIALIZED},    //SWITCH_PLUS
		{SWITCH_PLUS_PORT_DR_MIRROR,SWITCH_PLUS_PIN_MIRROR,INPUT,PULLUP,INITIALIZED}    //SWITCH_PLUS
		
		/*
		{PORT_A,0,INPUT,PULLUP,INITIALIZED},   // SWITCH_MINUS
		{PORT_A,1,INPUT,PULLUP,INITIALIZED}    //SWITCH_PLUS
			*/
};


